### ISSUE TITLE
How to use Resolve 17 recipe ?

### ISSUE THREAD

**Issue by adrienlabigne** [hovedkvarteret/autopkg-recipes#2]
Hi, I wanted to use your Resolve 17 recipe, because the manual import to munki is not working very well as the CFBundleIdentifier is not set, don't know why...

I modify DaVinciResolve17.download.recipe like this

```
<key>NAME</key>
<string>DaVinciResolve17</string>
<key>REG_FIRSTNAME</key>
<string>IT</string>
<key>REG_LASTNAME</key>
<string>Tech</string>
<key>REG_EMAIL</key>
<string>it.tech@heaj.be</string>
<key>REG_PHONE</key>
<string>081000000</string>
<key>REG_CITY</key>
<string>Namur</string>
<key>REG_COUNTRY</key>
<string>be</string>
```

and BlackMagicURLProvider.py
```
REQUIRED_REG_KEYS = [
    # "firstname",
    # "lastname",
    # "email",
    # "phone",
    # "city",
    # "country",
    "IT",
    "Tech",
    "it.tech@heaj.be",
    "081000000",
    "Namur",
    "be",
]
```

But i always got errors : 
<img width="416" alt="Capture d’écran 2021-10-07 à 23 21 10" src="https://user-images.githubusercontent.com/36637240/136463962-46bc712d-9b64-4c1e-9b07-1a7c6be13000.png">

Thanks !

**Comment by KWik** [comment]
In short you do not want to edit and run, but you want to make use of the override and trust functions.

On a clean, new machine I am doing this:

kwik@mac % autopkg repo-add http://github.com/hovedkvarteret/auto-pkg
...
kwik@mac % autopkg make-override DaVinciResolve17.munki.recipe                                                      
Override file saved to /Users/kwik/Library/AutoPkg/RecipeOverrides/DaVinciResolve17.munki.recipe

Then you correct the REG_* fields and run

kwik@mac % autopkg update-trust-info local.munki.DaVinciResolve17
Wrote updated /Users/kwik/Library/AutoPkg/RecipeOverrides/DaVinciResolve17.munki.recipe

After this you should be able to run the recipes as expected.

This is also mentioned  in the wiki:
https://github.com/autopkg/autopkg/wiki/AutoPkg-and-recipe-parent-trust-info
